apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wc4n
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wc4n
    app.kubernetes.io/part-of: ci10t-777-0045-app
  name: devfile-sample-wc4n
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wc4n
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wc4n
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0045-tenant/ci10t-777-0045-app/devfile-sample-wc4n@sha256:359eb63781bb2d675795eb399639435587b209c87418f73a877692254c9589a9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
